### ISSUE TITLE
Did mcuboot considered as base or reference?

### ISSUE THREAD

**Issue by otavio** [tock/tock-bootloader#5]
I saw this project and the mcuboot[1] project came to my mind as a good reference to be used as a base or design reference.

1. https://github.com/linaro-technologies/mcuboot

I thought it would be great to raise it now as the project is active and this can shorten the amount of effort need to add OTA and safe upgrade support.

**Comment by bradjc** [comment]
I've looked into mcuboot only briefly. I think for the purposes of Tock, we want to move away from having C code running in a trusted environment on our devices. We have a plan to build the bootloader on top of Tock, but progress has been slow on that front. There might be a middle-term solution that involves mcuboot, but it would need to have someone motivated to pursue it.

**Comment by otavio** [comment]
I understand. It does make sense to use Tock itself as the base for the bootloader in any case `mcuboot` does some clever things to provide atomic updates and it would be something very useful to have.

**Comment by alevy** [comment]
What about a non-C port of MCU-boot? To what extent does MCU boot fit Tock's model, and could we at least borrow the over-the-wire protocol and signing checks so Tock would work with the same tools...

**Comment by bradjc** [comment]
I think the first step would be adding mcu boot support to tockloader. But this bootloader is barely worked on as it is, and it seems to work well enough for Tock's use cases.
